## Integrantes: Grupo 10


- FELIPE ANTONIO BARJA CÁRCAMO
- CRISTIAN FELIPE BERNAL SALINAS
- SEBASTIAN ALEJANDRO LILLO ACOSTA
- IGNACIO ANDRÉS VALDEBENITO CÁCERES

# Instalación de librerías necesarias

In [805]:
import numpy as np

# Sección 1

### Estado inicial

En el siguiente cuadro se muestra el estado inicial del problema. Cada estado se compone de una matriz de tamaño 16x16. Los elementos de esta matriz pueden variar entre los valores 0 y 1 (Una matriz binaria).

In [806]:
# Set a random seed for reproducibility
np.random.seed(123)

# Generate a 16x16 matrix of random values between 0 and 1
initial_state = np.random.randint(2, size=(16,16))


In [807]:
# function that print a given matrix
def print_matrix(state):
  for row in state:
    print(row)

In [808]:
print_matrix(initial_state)

[0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
[0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
[1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
[0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
[1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
[1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
[1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
[1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
[1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
[0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
[0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
[0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
[0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
[0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0]


### Acción
Para este estado se define que una accion es intercambiar el valor de un elemento de tal forma que:

*   Si el elemento tiene un valor 1 se le asigna un valor 0
*   Si el elemento tiene un valor 0 se le asigna un valor 1

El siguiente codigo muestra como se realoza una acción en el elemento [0,0] del estado inicial.

In [809]:
copy_initial_state = np.copy(initial_state)
copy_initial_state[0, 0] = 1
print_matrix(copy_initial_state)

[1 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
[0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
[1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
[0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
[1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
[1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
[1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
[1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
[1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
[0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
[0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
[0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
[0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
[0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0]


### Función de expansión de nodos

Esta función recibe como parámetro un estado (matriz binaria) y devuelve una lista de todos los estados hijos posibles que se pueden obtener a partir de intercambiar los valores de cada uno de los elementos de la matriz.

Primero se crea una lista vacía para almacenar los hijos generados y se crea una copia del estado original. Luego, se realiza un ciclo doble que itera sobre los índices de las filas y columnas de la matriz. Para cada elemento de la matriz se intercambia su valor en la copia de la matriz new_state, se agrega la copia actualizada a la lista de hijos children y se restaura el valor original del elemento en la copia de la matriz.

La función swap_element recibe como parámetros una matriz binaria (matrix) y los índices de una fila (row_idx) y columna (col_idx). La función intercambia el valor del elemento en la posición indicada de la matriz, es decir, si el valor es 1 lo cambia por 0 y viceversa. Luego devuelve la matriz con el cambio realizado.

In [810]:
def expand_node(state):
    # Crear una lista vacía para almacenar los hijos generados
    children = []

    # Crear una copia del estado original
    new_state = state.copy()

    # Generar un hijo para cada elemento de la matriz
    for i in range(state.shape[0]):
        for j in range(state.shape[1]):
            # Intercambiar el valor del elemento en la copia de la matriz
            new_state = swap_element(new_state, i, j)

            # Agregar la copia actualizada a la lista de hijos
            children.append(new_state.copy())

            # Restaurar el valor original del elemento en la copia de la matriz
            new_state = swap_element(new_state, i, j)

    # Devolver la lista de hijos generados
    return children

def swap_element(matrix, row_idx, col_idx):
    if matrix[row_idx, col_idx] == 1:
        matrix[row_idx, col_idx] = 0
    else:
        matrix[row_idx, col_idx] = 1
    return matrix




### Estado Meta o final

Para el ejercicio se considera como estado meta (o final) la matriz que se genera al usar la semilla 124 en numpy. La cual se muestra a continuación.



In [811]:
# Set a random seed for reproducibility
np.random.seed(124)

# Generate a 16x16 matrix of random values between 0 and 1
final_state = np.random.randint(2, size=(16,16))

print_matrix(final_state)

[0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
[1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1]
[1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1]
[0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0]
[0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1]
[1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0]
[0 1 1 0 1 0 0 1 0 1 1 1 0 1 1 1]
[0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0]
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1]
[1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0]
[1 0 0 0 0 1 0 0 1 1 1 1 0 1 1 1]
[1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1]
[1 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1]
[0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
[0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 1]
[0 1 0 1 0 1 1 1 0 0 0 1 1 1 0 0]


### Función is_goal

Esta función recibe dos matrices de numpy state y final_state y retorna True si son iguales, es decir, si representan el mismo estado, y False en caso contrario.

La comparación entre las matrices se realiza con la función np.array_equal() de numpy, la cual devuelve True si ambas matrices tienen las mismas dimensiones y cada uno de sus elementos es igual. En este caso, se utiliza para comprobar si el estado actual es igual al estado final del problema, lo que indicaría que se ha encontrado la solución al problema.

In [812]:
def is_goal(state,final_state):
    return np.array_equal(state, final_state)

# Sección 2

## Metaheurística seleccionada: Algoritmo Genético.

El algoritmo genético es una técnica de búsqueda y optimización inspirada en la evolución biológica. En este tipo de algoritmos se utiliza una población de soluciones, las cuales evolucionan a través de generaciones. En cada generación se seleccionan soluciones (individuos) de la población actual, se combinan para generar nuevas soluciones y se aplican operadores de mutación para añadir diversidad a la población. De esta forma, se va explorando el espacio de soluciones en busca de la mejor.

En el caso del problema planteado, el algoritmo genético se utiliza para buscar una secuencia de acciones que permita llegar del estado inicial al estado final. Para ello, se crea una población inicial de estados, se evalúa su "aptitud" mediante la función de fitness que mide su distancia al estado final, y se aplican operadores de selección, cruzamiento y mutación para generar nuevas soluciones (estados). El objetivo es que, después de varias generaciones, la población evolucione hacia soluciones que estén cada vez más cerca del estado final, hasta encontrar una solución óptima. En este caso, la solución óptima es la secuencia de acciones que permite llegar del estado inicial al estado final con la menor cantidad de cambios de posición de las fichas posibles.

### Función de evaluación: fitness

La función evaluate_fitness se utiliza para evaluar la aptitud de un estado en el algoritmo genético. Recibe como argumentos el estado que se quiere evaluar (state) y el estado objetivo (final_state) que se quiere alcanzar.

En la implementación, se utiliza la operación de comparación == para comparar los elementos de state con los elementos de final_state. Esta operación devuelve una matriz booleana del mismo tamaño que state y final_state en la que cada elemento es True si los elementos correspondientes en state y final_state son iguales, y False en caso contrario.

La función np.sum se utiliza para sumar los elementos de la matriz booleana resultante. Como True equivale a 1 y False a 0, la suma representa el número de elementos en state que son iguales a los elementos correspondientes en final_state.

Este número de elementos iguales se utiliza como medida de aptitud del estado state. Cuanto mayor sea el número de elementos en común con final_state, mayor será la aptitud del estado state.

In [813]:
def evaluate_fitness(state, final_state):
    
    return np.sum(state == final_state)

### Función de selección de padres

Esta función utiliza el método del torneo para seleccionar los padres, que consiste en seleccionar de manera aleatoria algunos individuos de la población y evaluarlos para ver cuál tiene el mejor desempeño.

El tamaño del torneo se establece mediante el parámetro tournament_size, que representa la proporción de la población total que se utilizará para el torneo. En este caso, tournament_size se establece en 0.3, lo que significa que el tamaño del torneo será el 30% de la población total.

En cada iteración de la función, se seleccionan dos padres para el cruzamiento. Para cada padre, se realizan torneos utilizando la proporción de la población establecida por tournament_size. Los candidatos a padres se extraen aleatoriamente de la población, y el padre ganador se selecciona como el individuo con la mejor puntuación de aptitud en el torneo. Este proceso se repite dos veces para obtener los dos padres necesarios para el cruzamiento.

In [814]:
def select_parents(population, fitness_scores, tournament_size=0.3):

    parents = []
    for i in range(2):
        indices = np.random.choice(len(population), size=int(len(population)*tournament_size), replace=False)
        candidate_parents = population[indices]
        candidate_fitness_scores = fitness_scores[indices]
        winner_index = np.argmax(candidate_fitness_scores)
        parents.append(candidate_parents[winner_index])
        
    return parents

### Función de cruzamiento

Recibe como entrada una lista de dos padres (representados por matrices de números binarios) y devuelve un hijo generado por el cruzamiento de los padres. El método de cruzamiento utilizado en esta implementación es el de "un solo punto" (single-point crossover).

Primero, se realiza una copia del primer padre y se almacena en la variable child. A continuación, se selecciona un punto de corte (crossover_point) de forma aleatoria entre 1 y la longitud de la matriz menos 1. Este punto de corte divide la matriz en dos partes: una parte de la izquierda y otra de la derecha.

Luego, se copia la parte de la matriz correspondiente al segundo padre desde la posición 0 hasta la posición del punto de corte en la matriz del hijo. De esta forma, se intercambian las partes de los padres en el hijo a partir del punto de corte, creando una nueva combinación de genes. Finalmente, se devuelve la matriz resultante como el hijo generado por el operador de cruzamiento.

In [815]:
def crossover(parents):
    
    child = np.copy(parents[0])
    crossover_point = np.random.randint(1, len(child)-1)
    child[:crossover_point,:] = parents[1][:crossover_point,:]
    
    return child

### Función de mutación

La función mutate implementa el operador de mutación en el algoritmo genético. Recibe como entrada un hijo generado por el operador de cruzamiento y una tasa de mutación (mutation_rate) que indica la probabilidad de que cada bit de la matriz sea mutado.

En el cuerpo de la función, se itera sobre cada elemento de la matriz (cada bit) y se verifica si se debe mutar o no. La mutación se realiza con una probabilidad igual a la tasa de mutación. Si un elemento debe ser mutado, su valor se invierte (de 0 a 1 o de 1 a 0) para crear una nueva combinación de genes.

Finalmente, se devuelve la matriz mutada como el hijo resultante del operador de mutación.

In [816]:
def mutate(child, mutation_rate):

    for i in range(child.shape[0]):
        for j in range(child.shape[1]):
            if np.random.rand() < mutation_rate:
                child[i, j] = 1 - child[i, j]
                
    return child

### Algoritmo Genético

Esta función recibe como parámetros el tamaño de población (population_size), la probabilidad de mutación (mutation_rate) y el máximo de generaciones (max_generations). Además, recibe el estado inicial y el final del problema.

La población inicial se compone de una matriz binaria de tamaño nxn, donde el primer elemento de la población es el estado inicial y el resto de los elementos se generan aleatoriamente.

En cada generación del algoritmo, se evalúa la aptitud de cada estado en la población utilizando la función evaluate_fitness, que retorna el número de elementos en común entre el estado y el estado final objetivo. Luego, se seleccionan dos padres para el cruzamiento utilizando la función select_parents, que utiliza un torneo con tamaño de muestra proporcional a la población total.

A continuación, se realiza el cruzamiento y la mutación de los padres para generar un nuevo hijo utilizando las funciones crossover y mutate, respectivamente. El proceso se repite hasta que se genera una nueva población completa, y se repite para varias generaciones.

Finalmente, si se encuentra un estado que cumple con el objetivo, el algoritmo devuelve una lista (path) con los estados con mejor fitness visitados en cada generación. De lo contrario, devuelve None.

In [817]:
def genetic_algorithm(population_size, mutation_rate, max_generations, initial_state, final_state):
    
    n = initial_state.shape[0]
    population = np.concatenate((np.array([initial_state]), np.random.randint(2, size=(population_size-1, n, n))))
    
    state_path_list = []
    for generation in range(max_generations):
        
        fitness_scores = np.array([evaluate_fitness(state, final_state) for state in population])
        
        if is_goal(population[np.argmax(fitness_scores)],final_state):
            state_path_list.append(population[np.argmax(fitness_scores)])
            return state_path_list
        
        new_population = []
        for i in range(population_size//2):
            parents = select_parents(population, fitness_scores)
            child = crossover(parents)
            child = mutate(child, mutation_rate)
            new_population.append(child)
            new_population.append(np.copy(parents[0]))
        
        population = np.array(new_population)
        state_path_list.append(population[np.argmax(fitness_scores)])
        
    return None

Luego de definir nuestras funciones para el algoritmo genético, se llama a la función genetic_algorithm con los parámetros necesarios, así como con el estado inicial y final del problema.

Si la función genetic_algorithm encuentra una solución, se imprime en pantalla la generación en la que se encontró la solución y se muestra el path_list, que en realidad son los individuos con mejor fitness de cada generación. En caso contrario, se imprime que no se encontró una solución dentro del número máximo de generaciones.

Es importante destacar que path_list en realidad no es una lista de caminos, sino una lista de los individuos con mejor fitness de cada generación, lo que nos permite hacer un seguimiento del proceso de la evolución de la población.

In [834]:
population_size = 500
mutation_rate = 0.01
max_generations = 500
path_list = genetic_algorithm(population_size, mutation_rate, max_generations, initial_state, final_state)

if path_list is not None:
    print("Solución encontrada en la generación: " + str(len(path_list))+"\n")
    print("Lista de individuos con mejor fitness de cada generación: ")
    print(path_list)
else:
    print('No hay solución dentro de las '+ str(max_generations) + ' generaciones' )

Solución encontrada en la generación: 46

Lista de individuos con mejor fitness de cada generación: 
[array([[0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,

### Conclusión

Finalmente, el tamaño de la población, la probabilidad de mutación y la cantidad máxima de generaciones son parámetros clave en el algoritmo genético implementado y están estrechamente relacionados.

- El tamaño de la población determina la cantidad de individuos que se generan y evolucionan en cada generación. Una población más grande permite una exploración más amplia del espacio de soluciones, pero también puede aumentar el tiempo de cómputo.

- La probabilidad de mutación determina la tasa de mutación de los individuos en cada generación. Una probabilidad de mutación más alta permite una exploración más amplia del espacio de soluciones, pero también puede hacer que la evolución se vuelva caótica y divergente.

- La cantidad máxima de generaciones es el número de iteraciones que el algoritmo realizará antes de finalizar. Una cantidad máxima de generaciones más alta permitirá una búsqueda más exhaustiva del espacio de soluciones, pero también aumentará el tiempo de cómputo.

En general, estos parámetros deben ajustarse cuidadosamente para encontrar un equilibrio entre la exploración del espacio de soluciones y el tiempo de cómputo. Un tamaño de población más grande y una probabilidad de mutación más alta permiten una exploración más amplia del espacio de soluciones, pero pueden aumentar el tiempo de cómputo. Por otro lado, una cantidad máxima de generaciones más alta permite una búsqueda más exhaustiva del espacio de soluciones, pero también aumenta el tiempo de cómputo.