El laboratorio se dividirá en 2 secciones.
En la primera sección tendrán que definir las funciones necesarias para explorar un problema desde un estado inicial y reconocer si este estado es el estado final.(15 pts)

En la segunda sección se tendrá que implementar un algoritmo de búsqueda informado, el cual nos permita obtener el path desde un estado inicial hasta un estado final.(35 pts)

Finalmente, se asignará un puntaje de entre 0 y 10 puntos por la cantidad/calidad de los comentarios que se agreguen al código explicando cada uno de sus componentes. 

El Laboratorio deberá ser trabajado en grupos de entre 3 (min) y 5(max) estudiantes. La fecha de entrega del Lab 1 es el 24/04. La entrega se realizará a través del aula, antes de las 23.59 del dia 24/04.

#Instalación de librerías necesarias

In [1166]:
import numpy as np

#**Seccion 1**

#Estado

En el siguiente cuadro se muestra el estado inicial del problema. Cada estado se compone de una matriz de tamaño 16x16. Los elementos de esta matriz pueden variar entre los valores 0 y 1 (Una matriz binaria).

In [1167]:
# Set a random seed for reproducibility
np.random.seed(123)

# Generate a 16x16 matrix of random values between 0 and 1
initial_state = np.random.randint(2, size=(16,16))


In [1168]:
# function that print a given matrix
def print_matrix(state):
  for row in state:
    print(row)

In [1169]:
print_matrix(initial_state)

[0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
[0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
[1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
[0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
[1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
[1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
[1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
[1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
[1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
[0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
[0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
[0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
[0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
[0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0]


#Acción
Para este estado se define que una accion es intercambiar el valor de un elemento de tal forma que:

*   Si el elemento tiene un valor 1 se le asigna un valor 0
*   Si el elemento tiene un valor 0 se le asigna un valor 1

El siguiente codigo muestra como se realoza una acción en el elemento [0,0] del estado inicial.

In [1170]:
copy_initial_state = np.copy(initial_state)
copy_initial_state[0, 0] = 1
print_matrix(copy_initial_state)

[1 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
[0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
[1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
[0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
[1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
[1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
[1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
[1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
[1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
[0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
[0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
[0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
[0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
[0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0]


En base a esto se pide completar la funcóon *expand_node(state)*. Donde la funcion retorna una lista de todos los hijos que se pueden generar de un estado state dado. (10 pts)

In [1171]:
def expand_node(state):
    # Crear una lista vacía para almacenar los hijos generados
    children = []

    # Crear una copia del estado original
    new_state = state.copy()

    # Generar un hijo para cada elemento de la matriz
    for i in range(state.shape[0]):
        for j in range(state.shape[1]):
            # Intercambiar el valor del elemento en la copia de la matriz
            new_state = swap_element(new_state, i, j)

            # Agregar la copia actualizada a la lista de hijos
            children.append(new_state.copy())

            # Restaurar el valor original del elemento en la copia de la matriz
            new_state = swap_element(new_state, i, j)

    # Devolver la lista de hijos generados
    return children

def swap_element(matrix, row_idx, col_idx):
    if matrix[row_idx, col_idx] == 1:
        matrix[row_idx, col_idx] = 0
    else:
        matrix[row_idx, col_idx] = 1
    return matrix

children = expand_node(initial_state)




# Estado Meta

Para el ejercicio se considera como estado meta (o final) la matriz que se genera al usar la semilla 124 en numpy. La cual se muestra a continuación.



In [1172]:
# Set a random seed for reproducibility
np.random.seed(124)

# Generate a 16x16 matrix of random values between 0 and 1
final_state = np.random.randint(2, size=(16,16))

print_matrix(final_state)

[0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
[1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1]
[1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1]
[0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0]
[0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1]
[1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0]
[0 1 1 0 1 0 0 1 0 1 1 1 0 1 1 1]
[0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0]
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1]
[1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0]
[1 0 0 0 0 1 0 0 1 1 1 1 0 1 1 1]
[1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1]
[1 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1]
[0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
[0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 1]
[0 1 0 1 0 1 1 1 0 0 0 1 1 1 0 0]


Teniendo este estado meta, se requiere que implemente la función *is_goal(state)*. la cual devuelve un valor booleano true si el estado state es el estado meta. En caso de que no sea el estado meta la funcion debera devolvera un valor booleano false. (5 pts)

In [1173]:
def is_goal(state):
    return np.array_equal(state, final_state)

#**Seccion 2**

En esta esta seccion se debera implementar un algoritmo de busqueda. Para esto tendran que que implementar la función *evaluate(state)* la cual evalua el estado y retorna un el coste de este. Como recomendacion considere que cada elemento del estado el cual no sea igual al del estado meta incrementa en 1 el coste de este. (5 pts)

In [1174]:
def evaluate_fitness(population):
    """
    Evaluate the fitness of each individual in the population by comparing them to the final state.
    """
    fitness_scores = []
    for individual in population:
        fitness = np.sum(individual == final_state)
        fitness_scores.append(fitness)
    return np.array(fitness_scores)

Teniendo la función de evaluación ya desarrollada es posible implementar el algoritmo de busqueda informado. Para ello deberan escoger **una** (meta)heuristica* Y describir el algoritmo escogido cómo hemos descrito los algoritmos que hemos visto en clases. (15 pts)

*Algunas opciones de (meta)heuristicas pueden ser local search, genetic algorithm, tabu search, simulates annealing entre otros.


Despues deberan implementar el algoritmo en la función *heuristic(initial_state)*. Esta función recibe como parámetro el estado inicial y debe retornar como salida el conjunto de acciones que permita ir desde el estado inicial hasta el estado final. (10 pts)

In [1175]:
def is_goal(state, final_state):
    """Determina si el estado dado es el estado objetivo"""
    return np.array_equal(state, final_state)


In [1176]:

def fitness(state, final_state):
    """Evalúa la aptitud de un estado, retornando el número de elementos en común con el estado objetivo"""
    return np.sum(state == final_state)


In [1177]:

def select_parents(population, fitness_scores, tournament_size=3):
    """Selecciona los padres para el cruzamiento"""
    parents = []
    for i in range(2):
        indices = np.random.choice(len(population), size=tournament_size, replace=False)
        candidate_parents = population[indices]
        candidate_fitness_scores = fitness_scores[indices]
        winner_index = np.argmax(candidate_fitness_scores)
        parents.append(candidate_parents[winner_index])
    return parents


In [1178]:

def crossover(parents):
    """Realiza el cruzamiento de dos padres"""
    child = np.copy(parents[0])
    crossover_point = np.random.randint(1, len(child)-1)
    child[:crossover_point,:] = parents[1][:crossover_point,:]
    return child


In [1179]:

def mutate(child, mutation_rate):
    """Realiza la mutación de un hijo"""
    for i in range(child.shape[0]):
        for j in range(child.shape[1]):
            if np.random.rand() < mutation_rate:
                child[i, j] = 1 - child[i, j]
    return child


In [1180]:

def genetic_algorithm(population_size, mutation_rate, max_generations, initial_state, final_state):
    """Implementa el algoritmo genético para encontrar una solución al problema"""
    population = np.array([initial_state] * population_size)
    state_path_list = []
    for generation in range(max_generations):
        fitness_scores = np.array([fitness(state, final_state) for state in population])
        if is_goal(population[np.argmax(fitness_scores)], final_state):
            state_path_list.append(population[np.argmax(fitness_scores)])
            return state_path_list
        new_population = []
        for i in range(population_size//2):
            parents = select_parents(population, fitness_scores)
            child = crossover(parents)
            child = mutate(child, mutation_rate)
            new_population.append(child)
            new_population.append(np.copy(parents[0]))
        population = np.array(new_population)
        state_path_list.append(population[np.argmax(fitness_scores)])
    return None


In [1181]:
# def get_path(state, initial_state):
#     """Obtiene el camino de acciones para llegar desde el estado inicial al estado final"""
#     path = []
#     init_state_copy = np.copy(initial_state)
#     while not np.array_equal(state, init_state_copy):
#         for i in range(state.shape[0]):
#             for j in range(state.shape[1]):
#                 if state[i, j] != init_state_copy[i, j]:
#                     init_state_copy[i, j] = 1 - init_state_copy[i, j]
#                     path.append((i, j))
#                     break
#             else:
#                 continue
#             break
#     return path

Ya implementado el algoritmo se pide mostrar en pantalla los estados recorridos desde el estado inicial hasta el estado final (se recomienda utilizar el camino mas corto que hayan encontrado). (5 pts)

In [1182]:
# Set the parameters of the genetic algorithm
population_size = 100
mutation_rate = 0.05
max_generations = 1000

state_path_list = genetic_algorithm(population_size, mutation_rate, max_generations, initial_state, final_state)

if state_path_list is not None:
    print("Solución encontrada en la generación: " + str(len(state_path_list)))
else:
    print('No hay solución dentro de las '+ str(max_generations) + ' generaciones' )

No hay solución dentro de las 1000 generaciones
